--initial inserts for lookup tables
INSERT INTO SU_ROLES VALUES(100, 'Employee');
INSERT INTO SU_ROLES VALUES(200, 'Manager');
/
INSERT INTO SB_LANES VALUES(10, 'Backlog');
INSERT INTO SB_LANES VALUES(20, 'TODO');
INSERT INTO SB_LANES VALUES(30, 'In Progress');
INSERT INTO SB_LANES VALUES(40, 'Test');
INSERT INTO SB_LANES VALUES(50, 'Verify');
INSERT INTO SB_LANES VALUES(60, 'Done');
/
--Test Entries--
INSERT INTO SCRUM_USERS(USER_FN, USER_LN, USER_USERNAME, USER_PASSWORD, ROLE_ID, USER_EMAIL) 
VALUES ('Patrick', 'Onion', 'pusername', 'password', 200, 'jpwrunyan@hotmail.com');
INSERT INTO SCRUM_USERS(USER_FN,USER_LN,USER_USERNAME,USER_PASSWORD,ROLE_ID,USER_EMAIL) 
VALUES ('Mister','Rogers','musername','password',100,'brogers0101@gmail.com');
INSERT INTO SCRUM_USERS(USER_FN,USER_LN,USER_USERNAME,USER_PASSWORD,ROLE_ID,USER_EMAIL) 
VALUES ('Burly','Gerbil','busername','password',100,'jibbgh@gmail.com');
INSERT INTO SCRUM_USERS(USER_FN,USER_LN,USER_USERNAME,USER_PASSWORD,ROLE_ID,USER_EMAIL) 
VALUES ('Elvis','Yangster','eusername','password',100,'waveeyang@gmail.com');
/
--
--HERE BELOW NEEDS TO BE FIXED
INSERT INTO SCRUM_BOARDS(USER_ID,SB_NAME) VALUES (1,'Patrick Board'); 
INSERT INTO USERS_BOARDS(USER_ID,SB_ID) VALUES(1,1);
INSERT INTO SCRUM_BOARDS(USER_ID,SB_NAME) VALUES (2,'Ben Board'); 
INSERT INTO USERS_BOARDS(USER_ID,SB_ID) VALUES(2,3);
INSERT INTO SCRUM_BOARDS(USER_ID,SB_NAME) VALUES (3,'Jibril Board'); 
INSERT INTO USERS_BOARDS(USER_ID,SB_ID) VALUES(3,4);
INSERT INTO SCRUM_BOARDS(USER_ID,SB_NAME) VALUES (4,'Elvis Board'); 
INSERT INTO USERS_BOARDS(USER_ID,SB_ID) VALUES(4,5);
/
INSERT INTO SB_STORIES(SB_ID,SBS_DESCRIPTION,SBS_POINTS,SBL_ID) VALUES(1,'Finish ProjectTwo',50,2);
/
INSERT INTO SB_TASKS(SBS_ID,SBT_STATUS,SBT_DESCRIPTION) VALUES(1,0,'Do it. Do it now.');
/
COMMIT;
/